blogs/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter
from blogs.views import (
    blogListView,
    BlogDetailView,
    # confirm_order_payment
)

service_router = SimpleRouter()

urlpatterns = [
    path('', blogListView.as_view(), name='blog_list'),
    path('<slug:slug>/', BlogDetailView.as_view(), name='blog_detail'),
]

project2/urls.py
from django.contrib import admin
from django.urls import path, include
from project2 import settings
from django.conf.urls.static import static
from users.views import (
    contact_us,
    terms_and_conditions,
    privacy_policy,
    refund_policy,
    ship_and_delivery,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("users.urls")),
    path('services/', include("services.urls")),
    path('blogs/', include("blogs.urls")),
    path('contactus/', contact_us, name='contact_us'),
    path('privacy-policy/', privacy_policy, name='privacy_policy'),
    path('refund-policy/', refund_policy, name='refund_policy'),
    path('ship-and-delivery-policy/',
         ship_and_delivery, name='ship_and_delivery'),
    path('terms-and-conditions/',
         terms_and_conditions, name='terms_and_conditions'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/models.py
from django.db import models
from sorl.thumbnail import ImageField
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from users.models import User
from django.utils.translation import ugettext_lazy as _


class ProductCategory(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, null=True, blank=True)
    web_description = RichTextField(
        config_name='awesome_ckeditor', null=True, blank=True)
    priority = models.PositiveIntegerField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.priority is None:
            last_category = ProductCategory.objects.last()
            self.priority = last_category.id + 1 if last_category else 1
        if self.slug is None:
            self.slug = slugify(self.title)
        super(ProductCategory, self).save(*args, **kwargs)


class ProductSubCategory(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, null=True, blank=True)
    category = models.ForeignKey(
        ProductCategory, on_delete=models.CASCADE,
        related_name='sub_category')
    web_description = RichTextField(
        config_name='awesome_ckeditor', null=True, blank=True)
    priority = models.PositiveIntegerField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.title} - {self.category.title}"

    def save(self, *args, **kwargs):
        if self.priority is None:
            last_category = ProductSubCategory.objects.last()
            self.priority = last_category.id + 1 if last_category else 1
        if self.slug is None:
            self.slug = slugify(f"{self.title}{self.category.title}")
        super(ProductSubCategory, self).save(*args, **kwargs)


class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, null=True, blank=True)
    icon = models.ImageField(
        upload_to='uploads/images/services/products/icons/', null=True)
    banner = models.ImageField(
        upload_to='uploads/images/services/products/banners/', null=True)
    category = models.ForeignKey(
        ProductCategory, on_delete=models.CASCADE,
        related_name='products')
    sub_category = models.ForeignKey(
        ProductSubCategory, on_delete=models.CASCADE,
        related_name='products', null=True, blank=True)
    user_input_text = models.CharField(
        max_length=255, null=True, blank=True)
    web_description = RichTextField(
        config_name='awesome_ckeditor', null=True, blank=True)
    priority = models.PositiveIntegerField(null=True, blank=True)
    is_recommended = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    likes = models.IntegerField(default=392)
    dislikes = models.IntegerField(default=0)
    star_ratings = models.DecimalField(
        default=4.3, decimal_places=2, max_digits=5)
    total_review = models.IntegerField(default=289)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.priority is None:
            last_product = Product.objects.last()
            self.priority = last_product.id + 1 if last_product else 1
        if self.slug is None:
            self.slug = slugify(self.title)
        super(Product, self).save(*args, **kwargs)

    def low_attr(self):
        min_attr = ProductAttribute.objects.filter(
            product_id=self.id).order_by('price').first()
        return min_attr


class ProductAttribute(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE,
        related_name='attributes')
    title = models.CharField(max_length=255, null=True, blank=True)
    value = models.IntegerField(null=True, blank=True)
    price = models.DecimalField(
        decimal_places=2, max_digits=10, default=0)
    offer_price = models.DecimalField(
        null=True, blank=True, decimal_places=2, max_digits=10, default=0)
    is_recommended = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)


class ProductCategoryFaq(models.Model):
    product_category = models.ForeignKey(
        ProductCategory, on_delete=models.CASCADE,
        related_name='faqs')
    question = models.CharField(max_length=255)
    answer = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.product_category}: {self.question}"


class ProductFaq(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE,
        related_name='faqs')
    question = models.CharField(max_length=255)
    answer = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.product}: {self.question}"


class ProductImage(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE,
        null=True, related_name="images")
    image = ImageField(
        upload_to='uploads/images/product/product-images/')
    is_approved = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class ProductReview(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE,
        null=True, related_name="reviews")
    first_name = models.CharField(max_length=255, null=True, blank=True)
    last_name = models.CharField(max_length=255, null=True, blank=True)
    review_msg = models.CharField(max_length=255, null=True, blank=True)
    review_time = models.DateTimeField(null=True, blank=True)
    reply_msg = models.CharField(max_length=255, null=True, blank=True)
    reply_time = models.DateTimeField(null=True, blank=True)
    ratings = models.IntegerField(default=9)
    review_likes = models.IntegerField(default=0)
    review_dislikes = models.IntegerField(default=0)
    reply_likes = models.IntegerField(default=0)
    reply_dislikes = models.IntegerField(default=0)


class Order(models.Model):
    class Status(models.TextChoices):
        INITIATED = 'i', _('Initiated')
        IN_PROGRESS = 'p', _('In Progress')
        COMPLETED = 'c', _('Completed')
        NOT_COMPLETED = 'n', _('Not Completed')

    class SubStatus(models.TextChoices):
        INITIATED = 'i', _('Initiated')
        ORDER_CONFIRMED = 'oc', _('Order Confirmed')
        PAYMENT_FAILED = 'pf', _('Payment Failed')
        IN_PROGRESS = 'ip', _('In Progress')
        COMPLETED = 'c', _('Completed')
        NOT_COMPLETED = 'n', _('Not Completed')

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='order_items')
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE,
        related_name='order_items')
    slug = models.CharField(max_length=255, null=True, default=None)
    payment_done = models.BooleanField(default=False)
    status = models.CharField(
        choices=Status.choices, default=Status.INITIATED,
        max_length=1)
    sub_status = models.CharField(
        choices=SubStatus.choices, default=SubStatus.INITIATED,
        max_length=2)
    order_price = models.DecimalField(
        null=True, decimal_places=2, max_digits=10)
    qr_code = models.FileField(null=True, blank=True,
                               upload_to='uploads/qr_codes/orders/')
    payment_json = models.JSONField(blank=True, null=True)
    description = models.CharField(max_length=250, null=True, blank=True)
    status_timeline = models.JSONField(default=list)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.slug)

    def save(self, *args, **kwargs):
        self.slug = f"{self.id}{self.user.pk}{self.product.pk}"
        super().save(*args, **kwargs)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Growsmo{% endblock title %}</title>
	{% block meta_extend %}
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=0.8, shrink-to-fit=no" />
	<meta name="author" content="" />
	<meta name="theme-color" content="#ffcc33">
	<link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}" />
    {% endblock meta_extend %}

	<link rel="canonical" href="https://Growsmo.online/">

    {% block static_files %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock static_files %}

	<!-- Google tag (gtag.js) -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-P0XVQNXH35"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'G-P0XVQNXH35');
	</script>
</head>

<body>
{% block header_content %}
{% include 'navbar1.html' %}
{% endblock header_content %}
	
{% include 'modals.html' %}
{% block main_content %}

{% endblock main_content %}

{% block footer_content %}
<footer>
	<div class="container mb-0">
		<div class="row pt-3 pb-3">
			<div class="col-sm-12 col-md-4 col-lg-4 text-start">
				<ul><h5 class="mb-3 ftr_heading py-3">Quick Links</h5>
					<li class='ftr_list_item my-1'><a class="ftr_list_link" href="/">Home</a></li>
					<li class='ftr_list_item my-1'><a class="ftr_list_link" href="/blogs">Blog</a></li>
					{% if user.is_authenticated %}
					<li class='ftr_list_item my-1'><a class="ftr_list_link" href="{% url 'user_detail'%}">Profile</a></li>
					<li class='ftr_list_item my-1'><a class="ftr_list_link" href="{% url 'user_logout'%}">Logout</a></li>
					<li class='ftr_list_item my-1'><a class="ftr_list_link" href="{% url 'contact_us'%}">My Queries</a></li>
					{% else %}
					<li class='ftr_list_item my-1'><a class="ftr_list_link" href="" class="nav-link" data-bs-toggle="modal" data-bs-target="#signupmodal">Signup</a></li>
					<li class='ftr_list_item my-1'><a class="ftr_list_link" href="" class="nav-link" data-bs-toggle="modal" data-bs-target="#loginmodal">Login</a></li>
					{% endif %}
				</ul>
			</div>
			{% block footer_recommendation %}

			{% endblock footer_recommendation %}
			<div class="col-sm-12 col-md-4 col-lg-4 text-start">
				<ul><h5 class="mb-3 ftr_heading py-3">Policies</h5>
					<li class='ftr_list_item my-1'><a class="ftr_list_link" href="/terms-and-conditions/">Terms and condition</a></li>
					<li class='ftr_list_item my-1'><a class="ftr_list_link" href="/privacy-policy/">Privacy Policy</a></li>
					<li class='ftr_list_item my-1'><a class="ftr_list_link" href="/refund-policy/">Refund Policy</a></li>
					<li class='ftr_list_item my-1'><a class="ftr_list_link" href="/ship-and-delivery-policy/">Ship and Delivery Policy</a></li>
					<li class='ftr_list_item my-1'><a class="ftr_list_link" href="/contactus/">Help 24x7</a></li>
				</ul>
			</div>
		</div>
	</div>
	<p class="mb-0 py-2 bg-black">Copyright © Growsmo 2023</p>
</footer>
{% endblock footer_content%}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script>
function refresh_product_list(cat='', sub_cat=''){
	var csrf_token = '{{csrf_token}}';
	$.ajax({
		type: 'POST',
		url: `/services/${cat}/`,
		data: { sel_sub_cat: sub_cat },
		beforeSend: function(xhr) {
			xhr.setRequestHeader('X-CSRFToken', csrf_token);
		},
		success: function(data) {
			document.getElementById("product_list").innerHTML = data
		}
	});
}


</script>
</body>
</html>

templates/faqs.html
{% load static %}
{% if faqs %}
<section class="section-padding-40 faq-section pt-5 mb-5" itemscope itemtype="https://schema.org/FAQPage">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h4 class="mb-3">Frequently Asked Questions</h4>
                <div class="accordion" id="accordionExample">
                    {% for faq_item in faqs %}
                        <div class="accordion-item mb-3" style="border: 1px solid #e2dddd; border-radius: 4px;" itemscope itemprop="mainEntity" itemtype="https://schema.org/Question">
                            <p class="accordion-header" id="heading{{forloop.counter0}}">
                            <button style="font-weight: 500;" class="accordion-button p-2
                                {% ifequal 0 forloop.counter0 %} {% else %} collapsed {% endifequal %}" type="button"
                                data-bs-toggle="collapse" data-bs-target="#collapseheading{{forloop.counter0}}"
                                aria-expanded="{% ifequal 0 forloop.counter0%} true {% else %} false {%endifequal%}"
                                aria-controls="collapseheading{{forloop.counter0}}" aria-controls="collapseheading{{forloop.counter0}}"
                                itemprop="name">
                                {{ faq_item.question }}
                            </button>
                            </p>
                            <div id="collapseheading{{forloop.counter0}}" itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer"
                            class="accordion-collapse p-0 collapse {% ifequal 0 forloop.counter0 %} show {% endifequal %}"
                            aria-labelledby="heading{{forloop.counter0}}" data-bs-parent="#accordionExample">
                                <div class="accordion-body p-2" itemprop="text">
                                    {{ faq_item.answer | safe }}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>
{% elif static_faqs %}
<section class="section-padding-40 faq-section pt-5 mb-5" itemscope itemtype="https://schema.org/FAQPage">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h4 class="mb-3">Frequently Asked Questions</h4>
                <div class="accordion" id="accordionExample">
                    {% for key, value in static_faqs.items %}
                        <div class="accordion-item mb-3" style="border: 1px solid #e2dddd; border-radius: 4px;" itemscope itemprop="mainEntity" itemtype="https://schema.org/Question">
                            <p class="accordion-header" id="{{key}}">
                            <button style="font-weight: 500;" class="accordion-button p-2 {% if key == 'first' %} {% else %} collapsed {% endif %}"
                            type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{key}}"
                            aria-expanded="{%if key == 'first'%} true {% else %} false {%endif%}" aria-controls="collapse{{key}}"
                            aria-controls="collapse{{key}}" itemprop="name">
                                {{ value.question }}
                            </button>
                            </p>
                            <div id="collapse{{key}}" itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer"
                                class="accordion-collapse p-0 collapse {% if key == 'first' %} show {% endif %}" aria-labelledby="{{key}}"
                                data-bs-parent="#accordionExample">
                                <div class="accordion-body p-2" itemprop="text">
                                {{ value.answer | safe }}
                            </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endif %}

templates/help.html
{% extends 'base.html' %}

{% block title %}
Growsmo | 24x7 Help
{% endblock title %}

{% block main_content %}
<div class="container mb-5">
    {% if user.is_authenticated and queries %}
        <div class="accordion mt-5" id="accordionExample">
            <div class="accordion-item">
                <h2 class="accordion-header" id="headingOne">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                        your Queries
                    </button>
                </h2>
                <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        <div class="row mb-3">
                            {% for query in queries %}

                            <!-- Modal -->
                            <div class="modal fade" id="{{query.pk}}" tabindex="-1" aria-labelledby="{{query.pk}}Label" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                    <div class="modal-header">
                                        <div>
                                            <p class="card-title">{{query.fullname}}</p>
                                            <p class="card-subtitle mb-2">{{query.email}}</p>
                                            {% if query.is_solved %}    
                                                <span class="text-warning">Solved</span>
                                            {% else %}
                                                <span class="text-danger">Inprogress</span>
                                            {% endif %}
                                            <p class="card-text"><small class="text-muted">{{query.created_at}}</small></p>
                                        </div>
                                    </div>
                                    <div class="modal-body">
                                        <h6>Your Query</h6>
                                        {{query.comment}}
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">Go Back</button>
                                        {% if not query.is_solved %}
                                        <a type="button" href="{% url 'close_query' query.id %}" class="btn btn-primary btn-sm">Close this query</a>
                                        {% endif %}
                                    </div>
                                    </div>
                                </div>
                            </div>


                                <div class="card m-2" style="width: 18rem;">
                                    <div class="card-body">
                                        <p class="card-title">{{query.fullname}}</p>
                                        <p class="card-subtitle mb-2">{{query.email}}</p>
                                        {% if query.is_solved %}    
                                            <span class="text-warning">Solved</span>
                                        {% else %}
                                            <span class="text-danger">Inprogress</span>
                                        {% endif %}
                                        <p class="card-text"><small class="text-muted">{{query.created_at}}</small></p>
                                        <button type="button" class="btn btn-secondary btn-sm" data-bs-toggle="modal" data-bs-target="#{{query.pk}}">View Query</button>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

    <h3 class="mt-5">24x7 Help</h3>
    <p class="mb-1">Get in touch with us</p><br>
    <div class="row">
        <div class="col-sm-6 px-lg-5 px-sm-0 mb-5" style="text-align: justify;">
            At Growsmo, we are committed to providing you with the best possible shopping experience. We understand that questions and concerns
            can arise at any time, which is why our 24x7 Help Center is here to assist you around the clock. Whether you have inquiries 
            about our products, need assistance with your account, or require help with any other aspect of your shopping journey, we've got you covered.<br><br>
            <strong>contact Information</strong><br><br>
            <p class="card-text mb-1"><small class="text-muted">Phone : &nbsp;&nbsp;+917456840797</small></p>
            <p class="card-text mb-1"><small class="text-muted">Email : &nbsp;&nbsp;userquery.Growsmo@gmail.com</small></p>
            <p class="card-text mb-1"><small class="text-muted">Sector 59, Noida (UP)<br>India, 201301</small></p>
        </div>
        <div class="col-sm-6 px-lg-5 px-sm-0 mb-3">
            {% if messages %}
                {% for message in messages %}
                    <p class="alert alert-success text-center py-2 mb-4">{{message}}</p>
                {% endfor %}
            {% endif %}

            <form method="POST">
                {% csrf_token %}
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="fullname" placeholder="Ex. John" name="fullname"
                    {% if user.first_name %}    
                        value="{{user.first_name}} {{user.last_name}}"
                    {% endif %} required>
                    <label for="fullname">Full name</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="email" class="form-control" id="user_email" placeholder="email" name="email"
                    {% if user.email %}
                        value="{{user.email}}"
                    {% endif %} required>
                    <label for="user_email">Email address</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="phone" class="form-control" id="user_phone" placeholder="phone number" name="phone"
                    {% if user.phone_number %}
                    value="{{user.phone_number}}"
                    {% endif %} required>
                    <label for="user_phone">Phone number</label>
                </div>
                <div class="form-floating mb-3">
                    <textarea class="form-control" placeholder="Leave a comment here" name="comment" id="comment" style="height: 100px" required></textarea>
                    <label for="comment">Comments</label>
                </div>
                <div class="d-grid gap-2">
                    <button class="btn btn-success" type="submit">Send</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock main_content %} 

templates/navbar1.html
{% block first_navbar %}
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #ede3e3;">
  <div class="container px-0">
    <button class="navbar-toggler order-first ms-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
     <img src="https://prod-instaastro-static-files.s3.amazonaws.com/static/img/hamburger.svg">
    </button>
    <a class="navbar-brand mx-auto" href="/">Growsmo</a>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item me-2 ps-3"><a class="nav-link" href="{% url 'growsmo_home'%}">Home</a></li>
        <li class="nav-item me-2 ps-3"><a class="nav-link" href="{% url 'service_home'%}">Service</a></li>
        <li class="nav-item me-2 ps-3"><a class="nav-link" href="{% url 'blog_list'%}">Blog</a></li>
        {% if user.is_authenticated %}
        <li class="nav-item me-2 ps-3"><a class="nav-link" href="{% url 'user_detail'%}">{% if user.first_name%} {{user.first_name}} {% else %} Profile {% endif %}</a></li>
        <li class="nav-item me-2 ps-3"><a class="nav-link" href="{% url 'user_logout'%}">Logout</a></li>
        {% else %}
         <li class="nav-item me-2 ps-3"><a href="" class="nav-link" data-bs-toggle="modal" data-bs-target="#signupmodal">Signup</a></li>
          <li class="nav-item me-2 ps-3"><a href="" class="nav-link" data-bs-toggle="modal" data-bs-target="#loginmodal">Login</a></li>
        {% endif %}
        <li class="nav-item ps-3"><a class="nav-link" href="{% url 'contact_us'%}">Help</a></li>
      </ul>
    </div>
  </div>
</nav>
{% endblock first_navbar %}

templates/navbar2.html
{% block second_navbar %}
<div class="navbar navbar-expand-lg navbar-light" id="category_list">
  <ul class="container dflex mb-0">
    <li class="category_list_item"><a class="category_item_link" href="/services">Latest</a></li>
    {% for category in category_list %}
      <li class="category_list_item dnone-mobile mx-2"><a class="category_item_link" href="{% url 'category_detail' category.slug  %}">{{category.title}}</a></li>
    {% endfor %}
    <!-- if category list > 10 then -->
    <li class="nav-item dropdown category_list_item ms-3">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        More Categories
      </a>
      <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
        {% for category in category_list %}
        <li><a class="category_item_link dropdown-item" href="{% url 'category_detail' category.slug  %}">{{category.title}}</a></li>
        {% endfor %}
      </ul>
    </li>
    <!-- endif -->
  </ul>
</div>
{% endblock second_navbar %}

templates/user_detail.html
{% extends 'base.html' %}

{% block main_content %}
<div class="container my-5">
    <div class="card mb-3 border-0">
        <div class="card-body p-0">
            <h5 class="card-title">{{user.first_name}} {{user.last_name}}</h5>
            <p class="card-text"><b>Phone :</b> {{user.phone_number}}<br><b>Email :</b> {{user.email}}<br>
            Growsmo is currently verifying all payments manually. this can take upto 4 to 5 hours. regarding this if you have any query, contact us in help section</p>
            <p class="card-text"><small class="text-muted">Member since - {{user.date_joined}}</small></p>
        </div>
    </div>

    {% include 'services/order_list.html' %}

    {% if recommended_products %}
    <div class="container my-5">
        <h4 class="my-4">Recommended Products</h4>
        <div class="row mb-3">
            {% for product in recommended_products %}
                <div class="col-sm-12 col-xs-12 col-md-4 col-lg-4 col-xl-4 mb-4">
                    <a href="{% url 'product_detail' product.category.slug product.slug %}" class="product_item_link text-decoration-none text-dark">
                        <div class="product_card">
                            <div class="product_image col-3">
                                <img src="{{product.icon.url}}" class="img-fluid rounded-start" alt="...">
                            </div>
                            <div class="product_content col-9">
                                <h5 class="product_title" style="color: violet;">{{product.title}}</h5>
                                {% comment %} <p class="product_desc mb-2">{{product.web_description|safe|truncatewords:15}}</p> {% endcomment %}
                                <p class="product_price mb-0" style="font-weight: 500; color: green;">Price - Rs.{{product.min_price}} <del>Rs.{{product.max_price}}</del></p>
                                <p class="product_purchase mb-0 text-muted">Likes - {{product.likes}}<br>Dislikes - {{product.dislikes}}</p>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}

</div>
{% endblock main_content %}